### ISSUE TITLE
Cannot identify Image file ERROR

### ISSUE THREAD

**Issue by drdancm** [light-and-ray/sd-webui-video-extras-tab#2]
I'm afraid locating the input video is confusing.

1 I  tried dropping the video into the blank area - does not work
2 I tried putting the path of the folder (in case it processes multiple videos from folder) - does not work
3 I tried putting the full path (with video file name) in blank area - still nothing works.

I completely wrong about how this should be done.

Would please explain how to inform the program about the video file location.
The screen capture that you show does not help with this issue.

Thanks

**Comment by light-and-ray** [comment]
If you use windows, hold down Shift on your keyboard and right-click on file. In the context menu that pops up, select "Copy As Path." Then paste it into the textbox

**Comment by drdancm** [comment]
Unfortunately following your instructions:
Copy as Path is not a choice

When I manually write in the full path I get this error:

Exception: ffmpeg exited with code 1
I'm afraid I don't know what it means or how to fix it.

**Comment by light-and-ray** [comment]
Please send console log

**Comment by drdancm** [comment]
To my total surprise, I tested one more time with several  different video file and everything worked just fine. Tomorrow I will test with some other files including the one that failed, and let you know if that also works.
Possibly, some updates to Stability Matrix or A1111 is what made the difference.

Thanks !
