### ISSUE TITLE
sd MOV 2 MOW 

### ISSUE THREAD

**Issue by oldworker55** [light-and-ray/sd-webui-video-extras-tab#4]
run sd mov 2mov ,fault in promts 'This feature is in beta version!!!
It only supports Windows!!!
Make sure you have installed the ControlNet and IP-Adapter models.
![Uploading movie_bug.jpg…]()

**Comment by light-and-ray** [comment]
Mov2mov is not my extension. Ask here
https://github.com/Scholar01/sd-webui-mov2mov
